from pathlib import Path
r=Path.cwd();common=[('1','E11','141000','MPa','纤维向弹性模量'),('2','E22','11400','MPa','局部2向弹性模量'),('3','E33','11400','MPa','局部3向弹性模量'),('4','PR12','0.28','—','泊松比'),('5','PR13','0.28','—','泊松比'),('6','PR23','0.28','—','泊松比'),('7','G12','7100','MPa','12剪切模量'),('8','G13','7100','MPa','13剪切模量'),('9','G23','7100','MPa','23剪切模量'),('10','XT','2080','MPa','纤维拉伸强度'),('11','XC','1250','MPa','纤维压缩强度'),('12','YT','60','MPa','基体拉伸强度'),('13','YC','290','MPa','基体压缩强度'),('14','S12','110','MPa','12剪切强度；当前判据的τ13项也用此值'),('15','S13','110','MPa','保留旧材料卡槽位；当前判据未使用'),('16','S23','110','MPa','23剪切强度')]
a=[('17','DFT0','0.07','—','纤维拉伸触发后的固定损伤'),('18','DFC0','0.14','—','纤维压缩触发后的固定损伤'),('19','DMT0','0.2','—','基体拉伸触发后的固定损伤'),('20','DMC0','0.4','—','基体压缩触发后的固定损伤'),('21','SMT','0.9','—','基体拉伸对剪切刚度的影响系数'),('22','SMC','0.5','—','基体压缩对剪切刚度的影响系数'),('23','THETA','15','度','本示例 Bin 的角度；其余 Bin 各自不同'),('24','WPLUS','0.5','—','+θ 族占比，−θ 为 1−WPLUS'),('25','UPDATE','0','—','0 下一增量反馈损伤；1 当前增量反馈')]
b=[('17','GFT','133','N/mm','纤维拉伸断裂能'),('18','GFC','10','N/mm','纤维压缩断裂能'),('19','GMT','0.5','N/mm','基体拉伸断裂能'),('20','GMC','1.6','N/mm','基体压缩断裂能'),('21','ALPHA','1','—','旧版保留参数；当前判据公式固定，未读取其数值'),('22','SMT','0.9','—','基体拉伸对剪切刚度的影响系数'),('23','SMC','0.5','—','基体压缩对剪切刚度的影响系数'),('24','ETA_F','0.0001','步时间单位','纤维模式的黏性时间'),('25','ETA_M','0.005','步时间单位','基体模式的黏性时间'),('26','THETA','15','度','本示例 Bin 的角度；其余 Bin 各自不同'),('27','WPLUS','0.5','—','+θ 族占比'),('28','CAPF','1','—','纤维法向刚度折减上限'),('29','CAPM','1','—','基体法向刚度折减上限'),('30','UPDATE','0','—','0 下一增量反馈；1 当前增量及数值切线')]
def table(rows):return '| PROPS | 代码变量 | Bin0 值 | 单位 | 用途 |\n|---:|---|---:|---|---|\n'+'\n'.join('| '+' | '.join(row)+' |' for row in rows)+'\n'
text='# 当前 UMAT 材料参数（2026-09-27）\n\n下表数值取自两份 `Rebuild_PDM_*.inp` 的 `WCM_Tank1_Mat1_Bin0`。其它 Bin 保持相同的原始单层常数，只按材料分箱改变 THETA。参数从各自材料卡按顺序读取；A/B 使用当前源码中的公式和单位，没有把单层材料参数重新换算为 WCM 等效值。\n\n## 两版共用 PROPS(1:16)\n\n'+table(common)+'\n## A：直接刚度折减，25 项\n\n'+table(a)+'\n## B：线性软化与黏性滞后，30 项\n\n'+table(b)+'\n**计算单位**：模量、强度为 MPa；长度为 mm；B 断裂能为 N/mm；黏性系数与 `DTIME` 使用同一分析步时间单位。A 的固定损伤值与 B 的刚度折减上限均无量纲。\n\n**删去的材料卡项**：`damage_enabled` 开关、`schema` 与 `model_id`。子程序版本由所选 `.for` 决定；不使用旧版 restart。`UPDATE` 和 B 的 `CAPF/CAPM` 仍参与计算，予以保留。B 的 `ALPHA` 和共用 `S13` 维持旧槽位以免重排原始材料参数，并明确当前判据未使用。\n\nA 失效触发后按固定值折减；B 损伤可达到 1，刚度计算仍有 `1e-6` 下限。两版 SDV 语义见 [SDV说明](SDV说明.md)。\n'
(r/'wcm_hashin_umat/PROPS说明.md').write_text(text,encoding='utf-8')
for v,d in [('A','A_stiffness_reduction'),('B','B_energy_softening')]:
 p=r/'test'/d/'README.md';s=p.read_text(encoding='utf-8')
 s=s.replace('constants=28','constants=25').replace('constants=33','constants=30').replace('28 项','25 项').replace('33 项','30 项')
 s+='\n## 材料参数读法\n\n当前子程序在 `WCM_CHECK` 中逐项读取并命名 PROPS；完整槽位、单位和 Bin0 实际数值见 [PROPS说明](../../wcm_hashin_umat/PROPS说明.md)。已去掉材料卡中的损伤开关、schema 和 model_id，当前材料卡分别为 A25/B30 项。`UPDATE` 及 B 的刚度折减上限仍可配置。\n'
 p.write_text(s,encoding='utf-8')
p=r/'test/README.md';s=p.read_text(encoding='utf-8').replace('A 28 / B 33','A 25 / B 30');s+='\n两版材料参数逐项含义见 [PROPS说明](../wcm_hashin_umat/PROPS说明.md)。\n';p.write_text(s,encoding='utf-8')
p=r/'README.md';s=p.read_text(encoding='utf-8');s+='\n当前 A/B 材料常数为25/30项；[PROPS逐项说明](wcm_hashin_umat/PROPS说明.md)。\n';p.write_text(s,encoding='utf-8')
p=r/'wcm_hashin_umat/CHANGELOG.md';s=p.read_text(encoding='utf-8');s='# 2026-09-27 参数槽位与子程序排版\n\n保留旧单层参数槽位并逐项命名；A 从28精简为25项，B 从33精简为30项。移除损伤开关、材料卡 schema/model_id，保留UPDATE和B刚度上限。按材料检查、角度转换、应力及雅可比、Hashin判据、损伤更新、结果返回分段，现有调用公式不变。详情见 PROPS说明.md 与 audit_20260927/props_layout/。\n\n'+s;p.write_text(s,encoding='utf-8')
