C 测试专用：用真实原始UMAT验证0度单层退化公式未改变。
C 测试构建时仅重命名UMAT符号，不改原始计算表达式。
      SUBROUTINE LEGACY_EVAL(MODE,P,NP,OLD,E0,DE,DT,LC,
     1                       NEW,S,C)
      IMPLICIT NONE
      INTEGER MODE,NP,NV,JSTEP(4)
      CHARACTER*80 CMNAME
      DOUBLE PRECISION P(NP),OLD(24),NEW(24),E0(6),DE(6)
      DOUBLE PRECISION DT,LC,S(6),C(6,6),DDSDDT(6),DRPLDE(6)
      DOUBLE PRECISION SSE,SPD,SCD,RPL,DRPLDT,TIME(2),TEMP,DTEMP
      DOUBLE PRECISION PREDEF(1),DPRED(1),COORDS(3),DROT(3,3)
      DOUBLE PRECISION F0(3,3),F1(3,3),PNEWDT
      INTEGER I
      CMNAME='BASELINE'
      S=0D0
      C=0D0
      DDSDDT=0D0
      DRPLDE=0D0
      SSE=0D0
      SPD=0D0
      SCD=0D0
      RPL=0D0
      DRPLDT=0D0
      TIME=0D0
      TEMP=0D0
      DTEMP=0D0
      PREDEF=0D0
      DPRED=0D0
      COORDS=0D0
      DROT=0D0
      DO I=1,3
          DROT(I,I)=1D0
      END DO
      F0=DROT
      F1=DROT
      JSTEP=(/1,1,0,0/)
      PNEWDT=1D0
      NEW=OLD
      IF(MODE.EQ.1) THEN
          NV=12
          CALL LEGACY_A(S,NEW,C,SSE,SPD,SCD,RPL,DDSDDT,
     1       DRPLDE,DRPLDT,E0,DE,TIME,DT,TEMP,DTEMP,PREDEF,
     2       DPRED,CMNAME,3,3,6,NV,P,NP,COORDS,DROT,
     3       PNEWDT,LC,F0,F1,1,1,1,1,JSTEP,1)
      ELSE
          NV=24
          CALL LEGACY_B(S,NEW,C,SSE,SPD,SCD,RPL,DDSDDT,
     1       DRPLDE,DRPLDT,E0,DE,TIME,DT,TEMP,DTEMP,PREDEF,
     2       DPRED,CMNAME,3,3,6,NV,P,NP,COORDS,DROT,
     3       PNEWDT,LC,F0,F1,1,1,1,1,JSTEP,1)
      END IF
      END
